### ISSUE TITLE
Pretty Display Name for Test Cases stopped working in Visual Studio 2019

### ISSUE THREAD

**Issue by urig** [xunit/visualstudio.xunit#155]
## Steps to reproduce
1. Open Visual Studio 2019
2. Create a new .Net Framework Class Library project
3. Manage Nuget packages and add `xunit` (v2.4.1) and `more.xunit.runner.visualstudio` (v2.3.1).
4. Create a new `[Fact]` method in a class. Give it a "pretty" name. Ex: `this_test_has_a_pretty_nameX21()`.
5. Add an `app.config` file that enables pretty names like so:
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <appSettings>
    <add key="xunit.methodDisplay" value="method" />
    <add key="xunit.methodDisplayOptions" value="all" />
  </appSettings>
</configuration>
```
6. Open the Test Explorer window.

## Expected Behavior
The test should appear in the window with a pretty name: `this test has a pretty name!`

## Actual Behavior
The test appears in the window with an ugly name: `this_test_has_a_pretty_nameX21` :(
Please see this screenshot:
![image](https://user-images.githubusercontent.com/47077649/60818491-6d2fc100-a1a6-11e9-8a36-1d268606b37b.png)

## Note
If you repeat the exact steps above in Visual Studio 2017, you get the expected behavior.

## Repo with repro
Can be found here: https://github.com/urig/xunit-bug-repro

**Comment by onovotny** [comment]
Please report this using the VS feedback tool. This is likely an issue with the way they discover tests using source instead of via discovery.
 
I don’t think there’s much we can do as it’s a VS issue.

**Comment by urig** [comment]
Thanks for the super fast response @onovotny .

Will do. Just want to contribute one more bit of info - This also happens when looking at tests through R#'s Unit Test Sessions window. Does this change anything?

**Comment by onovotny** [comment]
They have their own runner, I have no idea.

**Comment by bradwilson** [comment]
Both Resharper and VS's Source Based Discovery (as of this writing) were hand-written and don't follow the standard discovery system that we've provided for runner authors. Therefore you can't assume that anything they do is "standard" or "normal". When you hit edge cases that only affect those runners, we're pretty much always going to have to tell you to bring the issue up with them.

The best way to know whether the issue with source-based discovery is them or not, look for the differences you see in the test list before and after you build the project.

If you want to use source-based discovery, make sure both of these check boxes are checked:

![VS 2019](https://user-images.githubusercontent.com/16944/60822351-20be9400-a15a-11e9-8258-d6db16c2aa9b.PNG)

Alteratively, if you find source-based discovery doesn't work well for you because of issues like this, you can turn it off entirely with that first check box.

**Comment by urig** [comment]
Many thanks @bradwilson . I can confirm that turning off Source Based Discovery, as you've suggested, has resolved the issue.

I've reported the Problem in VS Developer Community forums: https://developercommunity.visualstudio.com/content/problem/643819/xunits-pretty-display-name-for-test-cases-feature.html

Closing this issue now.
