### ISSUE TITLE
Skip attribute for [Theory] vs. [Fact] shows inconsistent test count 

### ISSUE THREAD

**Issue by rockbender** [xunit/visualstudio.xunit#199]
Environment:
Windows, VS Code (1.42.1), and dotnet (3.1.100).

Issue:
Test run CLI summary shows inconsistent test count when a Fact is skipped vs. when a Theory is skipped.

Steps to Repro:
1.  Create a Fact test
2. Create a Theory test with two Inline data
3. Notice the test summary's test count stats show Total Test 3
3. Mark Fact test as to skip, notice that summary shows Total Test 3, Skipped 1
4. Undo Fact test skip
5. Mark Theory as to skip, notice that summary shows Total Test 2, Skipped 1

Expected:
Step 5 above should show Total Test 3, Skipped 2 (attributing to the two inline data row)

Additional Note:
InlineData skip shows the correct count.

**Comment by bradwilson** [comment]
This is working as expected.

When a whole theory is skipped, none of the data items is enumerated, and you get a single "skip" for the entire theory. It would be wasteful and counterproductive (and potentially broken behavior, since we don't know why the theory was skipped) to enumerate the theory's data, just to provide a "consistent" count of skips (doubly so since our philosophical view of skipped tests is that they should have a very short life; meaning, we consider it to be a process "smell" if you check skipped tests into source control).

**Comment by rockbender** [comment]
Thanks for addressing the inconsistency with skipped test count and the behaviour makes sense. 

There is yet another issue. This is with the Total test count. If you skip a Fact, the total test count doesnt change which is fine but when a Theory is skipped the Total test count is dropped by 1. 

I think the Total Test count shouldn't change when a Theory is skipped,

**Comment by bradwilson** [comment]
This can't be fixed, for the same reason.
