### ISSUE TITLE
Can output be captured from within IClassFixture<T>?

### ISSUE THREAD

**Issue by jdvor** [xunit/visualstudio.xunit#214]
As outlined here https://xunit.net/docs/capturing-output.html the message sink is indeed injected into fixture constructor (the type is `Xunit.Sdk.TestFrameworkProxy.MessageSinkWrapper`), but none of the messages sent to it are visible anywhere.
The documentation does not state that IClassFixture extensibility is supported or should work, on the other hand some conforming type is injected into the constructor.

Is there any way how to capture output from class fixtures?

xunit: 2.4.1
netcoreapp2.2
VS: Microsoft Visual Studio Enterprise 2019 Version 16.5.1

**Comment by rvvincelli** [comment]
Hi, thanks for this clarification; using the sink works for me (xunit 2.4.1, VS19 16.8.2), diag messages show up in the console after turning on the setting in the xunit conf. Tx,

**Comment by bradwilson** [comment]
I am closing this issue for age, and due to the fact that the requested feature(s) are now available in v3.

- If you want to write output from a fixture, you can do that now via `TestContext.Current.TestOutputHelper?.Write`. Note that this will only work when a test is running, hence the need to use `?.` on the tail end of `TestOutputHelper`, since that will be `null` when you're not currently running a test.

- If you want to capture `Debug.Write...`, you can do that in v3 with `[assembly: CaptureTrace]`. This will capture both `Trace` (all the time) and `Debug` (only for debug builds) and funnel that into the output stream of the test.

**Comment by techmantel** [comment]
I'm trying to use this `TestContext.Current.TestOutputHelper?.Write` from a `ICollectionFixture<>` in xunit.v3 assuming it would work the same as you described above,  but that `TestOutputHelper` is never anything else than `null`.

Should it be possible to use it from that kind of class too, and what could I be doing wrong if it should work?

**Comment by bradwilson** [comment]
@techmantel It depends on where you're using it in the fixture.

- If you're in the context of a running test, then it should work.
- If you're not (for example, if you're logging during fixture creation/cleanup, or from a worker thread), then it won't work.

**Comment by techmantel** [comment]
Yeah, that I understood from the comments and docs, but even though I spin up a task with a tight loop inside the fixture's `InitializeAsync` still it's never set.
One thing that I also should mention is that the fixture is inside another assembly, if that matters.

**Comment by bradwilson** [comment]
Two thoughts, not sure which one applies.

- Inside InitializeAsync, it will always be null, because this method call is never in the context of a specific test.
- If you're trying to "save" `ITestOutputHelper` for later, don't. Similarly, don't both trying to save the result of `TestContext.Current`, either, because it's a snapshot in time. You should always be directly calling `TestContext.Current.TestOutputHelper` at the exact moment you want to write a message.

**Comment by techmantel** [comment]
Yeah, I understand those points and haven't done it that way either.

The code I tried to test the output with inside the `InitializeAsync` is this, assuming that the context's output helper will be there when the actual test is executed.

```

Task.Run(() =>         
{             
    while (true)
    {
         TestContext.Current.TestOutputHelper?.Write("HI!");
         Thread.Sleep(1);
    }
});
```

**Comment by techmantel** [comment]
Oh, wait. I missed this part
>or from a worker thread), then it won't work.

So this means that the only way then is using the trace thingie?

**Comment by bradwilson** [comment]
Right, the best way to write messages outside the context of a test is to use a diagnostic message (via `TestContext.Current.SendDiagnosticMessage`) and make sure diagnostic messages are enabled in configuration. The message won't have any test relationship in this case, and will only be viewable while the test is running (output messages are put into the reports, when enabled, but diagnostic messages are considered ephemeral and not part of reporting).
