### ISSUE TITLE
Tests in the same collection can get run in parallel with one another

### ISSUE THREAD

**Issue by airbreather** [xunit/visualstudio.xunit#215]
Tested with Visual Studio 2019 Enterprise 16.5.4 and with Visual Studio 2019 Enterprise 16.6.0.

xUnit package versions are in the `PackageReference`s of the .csproj file included in the repro below.

# Repro Steps
1. Close all instances of Visual Studio.
1. Make a new folder.
1. Create text files "Test.cs" and "ClassLibrary0.csproj" in that folder (contents are listed below).
1. Open ClassLibrary0.csproj in Visual Studio.
1. Wait for the project to finish loading.
1. Bring up "Test.cs" in the editor.
1. Right-click the blank line between "Test1" and "Test2" > "Run Tests"
    - Note: both tests pass, and it takes about 200ms to run both.
1. Rename "Test2" to "Test3".
1. Right-click the blank line between "Test1" and "Test2" > "Run Tests"
    - Note: one test passes, the other fails, and it takes about 100ms to run both.

## Observations
- Renaming `Test3` back to `Test2` doesn't seem to fix it.
- Run All Tests doesn't seem to fix it.
- If I see it fail, then close the solution, then open the project back up again, the issue seems to go away until I rename something again or add a new test.
- `dotnet test` seems to work fine.
- Every combination I've used to run these tests from the Test Explorer window seems to work fine.
- MSTest seems to handle this properly.
    - When converting these tests to use their framework, I get consistent expected behavior:
        - `[assembly: Parallelize(Scope = ExecutionScope.ClassLevel)]`, everything works
        - `[assembly: Parallelize(Scope = ExecutionScope.MethodLevel)]`, everything fails

## Test.cs
```csharp
using System.Threading;

using Xunit;

public class Test
{
    private static readonly object LockObject = new object();

    [Fact]
    public void Test1() => Run();

    [Fact]
    public void Test2() => Run();

    private static void Run()
    {
        bool lockTaken = false;
        Monitor.TryEnter(LockObject, 0, ref lockTaken);
        try
        {
            Assert.True(lockTaken);
            Thread.Sleep(100); // increase this until it's consistent for your machine
        }
        finally
        {
            if (lockTaken)
            {
                Monitor.Exit(LockObject);
            }
        }
    }
}
```

## ClassLibrary.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.6.1" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1" />
  </ItemGroup>

</Project>
```

**Comment by bradwilson** [comment]
My best guess is that this is a bug caused by VSTest.

What I believe is happening is this:

- The first time tests are run, it knows about `Test1` and `Test2`
- You edit the source but don't rebuild (this is an important factor)
- You ask to run a limited number of tests (that is, everything in class `Test`)
- It then asks us to run `Test1` and `Test2`
- It doesn't know about `Test3`, but we report that during re-discovery (and it removes `Test2`, since that was not discovered)
- It immediately then issues a _second_ request for us to run the newly discovered `Test3`, which runs in parallel with the request to run the existing `Test1` and non-existing `Test2`

Thus, they have defeated our anti-parallel measures by asking us to run these things separately and distinctly from one another, but it does so at nearly the exact same time.

There's nothing we can do here. The buggy behavior belongs to the way VSTest has issued the execution requests. We're just doing what they asked us to do.

**Comment by bradwilson** [comment]
(The workaround, by the way, is to ensure you build and see the discovery completed in Test Explorer before running.)
