### ISSUE TITLE
not able to run tests after updating xunit.runner.visualstudio to version 2.4.2

### ISSUE THREAD

**Issue by buzhidao77** [xunit/visualstudio.xunit#219]
version 2.4.1 has been working fine. 
After updating to 2.4.2, dotnet test is giving the following error:

`Unable to find /Users/user/dev/project/Commontests/bin/Debug/netcoreapp3.1/testhost.dll. Please publish your test project and retry.

Test Run Aborted.`

**Comment by clairernovotny** [comment]
Do you have a repro project?

**Comment by chtoucas** [comment]
If your project compiles fine but fails to execute the tests, I would suspect a problem with Microsoft.NET.Test.Sdk, especially when it complains about a missing testhost.dll. Do you reference the last version (v16.6.1)?

**Comment by chtoucas** [comment]
@buzhidao77 I honestly don't know, but it's true that with 2.4.1 "dotnet test" worked fine without it.

**Comment by bcronje** [comment]
Exact same issue here. Is the "official" fix to install `Microsoft.NET.Test.Sdk` ? This was not required for `2.4.1`

**Comment by savedbygrace19** [comment]
Seeing this as well - worse, however, is while adding the Test.Sdk package fixes things on my dev box, it does not fix things on my Jenkins agent. I can't for the life of me figure out how to fix things on that build agent...

**Comment by bender2k14** [comment]
> Do you have a repro project?

Here is a [repro project](https://github.com/xunit/visualstudio.xunit/files/4899136/MWE.zip) @clairernovotny.

After building, the contents of `Output -> Tests` essentially says
```
TestPlatformException:
Unable to find `{path to repo}\Tests\bin\Debug\netcoreapp3.1\testhost.dll`.
Please publish your test project and retry.
```

Here is my full output.
```
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Unable to find C:\Users\twilliams\Downloads\MWE\Temp\Tests\bin\Debug\netcoreapp3.1\testhost.dll. Please publish your test project and retry.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostPath(String runtimeConfigDevPath, String depsFilePath, String sourceDirectory)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
```

**Comment by clairernovotny** [comment]
Closing as the latest test sdk reference is the fix.

**Comment by bender2k14** [comment]
@clairernovotny, I am confused.  Can you help clarify something for me?

Is `Microsoft.NET.Test.Sdk` necessary for `xunit.runner.visualstudio` to work correctly or is it possible to use `xunit.runner.visualstudio` without `Microsoft.NET.Test.Sdk`?

**Comment by Tino92** [comment]
Seems like version 2.4.1 has a dependency to Microsoft.NET.Test.Sdk (>= 15.0.0), which has been removed in version 2.4.2 and 2.4.3.

Reference: https://www.nuget.org/packages/xunit.runner.visualstudio/2.4.1

@clairernovotny, why was the dependency removed, when it seems like you need the Test.Sdk for xunit.runner.visualstudio to work?

**Comment by clairernovotny** [comment]
The test SDK should be brought in directly by your project, not the xUnit adapter.

**Comment by bender2k14** [comment]
Thanks for the response @clairernovotny.  Unfortunately, I am still confused.  Could you elborate?

My understanding of your comment is that I should add a direct dependency from my test project to `Microsoft.NET.Test.Sdk`, but I should not add a direct dependency to `xunit.runner.visualstudio`.  Am I understanding your comment correctly?

I want to see my tests in Visual Studio's Test Explorer.  How can I get them to appear there without directly depending on `xunit.runner.visualstudio`?

Also, why do you say that I should add a direct dependency from my test project to `Microsoft.NET.Test.Sdk`?  Does `xunit` or `xunit.runner.visualstudio` require this NuGet package in order to work correctly?

**Comment by clairernovotny** [comment]
You need both references.

**Comment by bender2k14** [comment]
Thanks @clairernovotny.  Your answers continue to be a bit terse from my perspective.  Like the others, I will unpack it by explaining how I understand it to make sure we are communicating effectively.

My understanding of...
> You need both references.

...is that you are answering my question in https://github.com/xunit/visualstudio.xunit/issues/219#issuecomment-668334362...
> Is `Microsoft.NET.Test.Sdk` necessary for `xunit.runner.visualstudio` to work correctly or is it possible to use `xunit.runner.visualstudio` without `Microsoft.NET.Test.Sdk`?

...by saying that `Microsoft.NET.Test.Sdk` is necessary for `xunit.runner.visualstudio` to work correctly.

If `Microsoft.NET.Test.Sdk` is necessary for `xunit.runner.visualstudio` to work correctly, then why doesn't `xunit.runner.visualstudio` have a NuGet package dependency on `Microsoft.NET.Test.Sdk`?

**Comment by bcronje** [comment]
As pointed out by @Tino92 and others, 2.4.1 brought the dependency with xunit install, now the user have to do it manually. Seems like a strange decision to remove it from 2.4.2/3. At a minimum I would expect this to be documented somewhere, which I don't believe it currently is, unless I overlooked it.

From a user point of view, I was using 2.4.1 without any issues, and after upgrading to 2.4.2 in the same projects running my tests stopped working. Seems like a breaking change to me.

**Comment by buzhidao77** [comment]
from 2.4.1 to 2.4.2 is supposed to be a non-breaking change, right?

**Comment by bender2k14** [comment]
It is supposed to be a non-breaking change if the versions numbers are to satisfy [semantic versioning](https://semver.org/).  Maybe version numbers for `xunit.runner.visualstudio` do not follow semantic versioning.

**Comment by bender2k14** [comment]
Are you saying that it is impossible to start using semantic versioning for versions of software released after the existence of semantic version?

**Comment by TysonMN** [comment]
@bradwilson, in https://github.com/xunit/xunit/issues/1986#issuecomment-539090954, you said that you don't want to introduce breaking changes (without mention on how the version number changes).

Do you feel the same way about the change discussed in this issue?

(In case it is unclear, the change being discussed in this issue was breaking for many people including myself.)

**Comment by bradwilson** [comment]
@TysonMN asked:

> Do you feel the same way about the change discussed in this issue?

My opinion is irrelevant. @clairernovotny sets the versioning policy for this project.

**Comment by TysonMN** [comment]
Thanks @bradwilson.  That is good to know.  It is also refreshing to receive a quickly and clear response.  Thanks! :)

Would you mind answering a non-opinion question?

I asked @clairernovotny several questions above, but unfortunately I struggled to fully understood her answers.

This is the main question, which I asked in https://github.com/xunit/visualstudio.xunit/issues/219#issuecomment-668334362.

> Is `Microsoft.NET.Test.Sdk` necessary for `xunit.runner.visualstudio` to work correctly or is it possible to use `xunit.runner.visualstudio` without `Microsoft.NET.Test.Sdk`?

**Comment by clairernovotny** [comment]
> `Microsoft.NET.Test.Sdk` is 100% required.... it's in the default template for the class library. The reason why we don't depend on it, and rely on the test library to add it, is that it updates with every release of VS / the .NET SDK to add new functionality. By having us depend on it as a transitive reference, people will be less likely to keep it updated.

**Comment by TysonMN** [comment]
Hello @clairernovotny!  Thanks for the quick and clear response as well.  I perfectly understand the answer to my question now.

> The reason why we don't depend on it, and rely on the test library to add it, is that it updates with every release of VS / the .NET SDK to add new functionality. By having us depend on it as a transitive reference, people will be less likely to keep it updated.

Wouldn't that be a good use case for adding `Microsoft.NET.Test.Sdk` as a dependency using the [floating version](https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution#floating-versions) `*`?

Specifically, that would look like this in the `csproj` file.
```xml
<ItemGroup>
  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="*" />
</ItemGroup>
```

Then the default behavior would be that users of `xunit.runner.visualstudio` always depend on the latest version of `Microsoft.NET.Test.Sdk` just like you want.  If any user would prefer to have (perfectly) deterministic builds, then they can take advantage of the [nearest wins](https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution#nearest-wins) feature by adding a top-level reference to a specific version of `Microsoft.NET.Test.Sdk`.

If it would help, I can contribute a PR that makes this change.

---

I was curious to find the exact commit in which the change being discussed in this issue occured.  I think it happened in [this commit](https://github.com/xunit/visualstudio.xunit/commit/15bf4542325e44eb68f7856a422e27ef7d92ccc0) when [this line from the deleted `nuspec` file](https://github.com/xunit/visualstudio.xunit/commit/15bf4542325e44eb68f7856a422e27ef7d92ccc0#diff-88dc7c9cc6976595a97a9542761d90a2d3042be280399656512617f6d610b115L17) was not moved to [the `csproj` file](https://github.com/xunit/visualstudio.xunit/commit/15bf4542325e44eb68f7856a422e27ef7d92ccc0#diff-af5953efa5b5792d90ea74a6c6fee47093d654900314ab438c9cd1dc42178f39).

**Comment by clairernovotny** [comment]
That only helps with restore time, at pack time, the current version is encoded in.

**Comment by TysonMN** [comment]
Ah, I see that now.  I just tested, and the behavior is exactly as you describe.

[The `nuspec` file supports ranges](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#code-try-3:~:text=References%20in%20.nuspec%20files), and ranges are copied from the `csproj` file.  However, I think the default behavior (since [version 2.8 of NuGet](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-2.8)) is to resolve the lowest dependency in a range.  In particular, I just tested that the NuGet package management GUI in version 16.8.2 of Visual Studio does not suggest updating a dependency to the top of its range.

-----------------

Here is my understanding of the situation.

`Microsoft.NET.Test.Sdk` is a runtime dependency of `xunit.runner.visualstudio`.  It was also a compile-time dependency in version 2.4.1, but it is not a compile-time dependency in version 2.4.2.

What @clairernovotny / `xunit.runner.visualstudio` really wants is not just a runtime dependency on `Microsoft.NET.Test.Sdk` but a runtime dependency on the latest version of `Microsoft.NET.Test.Sdk`.  (AFAIK) There is no way to currently express that a dependency of a NuGet package should resolve to its latest version for all future users of that NuGet package _from within that same NuGet package_.

As a workaround for this missing NuGet feature, @clairernovotny has decided to remove the compile-time dependency on `Microsoft.NET.Test.Sdk`.  Since `Microsoft.NET.Test.Sdk` is still a runtime dependency, this forces users to add a direct reference on `Microsoft.NET.Test.Sdk`.  The typical way to do this is through the NuGet package manager GUI in Visual Studio.  This will add a direct reference to a specific version of `Microsoft.NET.Test.Sdk`.  When a new version of `Microsoft.NET.Test.Sdk` is released, the same GUI will suggest updating to that newer version.  (Alternatively, a user could add a direct reference to to `Microsoft.NET.Test.Sdk` using the floating version `*`, which will also resolve to the latest version at the cost of somewhat less deterministic test runs.)

@clairernovotny, have you told the [NuGet team](https://github.com/NuGet) about your use case and their lack of support for it?  I would be particularly interested if there was a public issue to which I could subscribe where you or someone else has suggested a new features to NuGet that could replace the present hack.  The most obvious solution to me is to allow floating versions in `nuspec` files, but [it seems the lack of that feature is intentional](https://github.com/NuGet/Home/issues/7658#issuecomment-450016822).  If such an issues doesn't exist, then I would be willing to create one.  (One idea is adding a new kind of dependency to a NuGet package that requires a direct reference to that dependency from the top level.)

**Comment by bradwilson** [comment]
> What @clairernovotny / xunit.runner.visualstudio really wants is not just a runtime dependency on Microsoft.NET.Test.Sdk but a runtime dependency on the latest version of Microsoft.NET.Test.Sdk.

It's probably more accurate to say that it's VSTest which wants the latest versions of those things. 😉 And since the version of `xunit.runner.visualstudio` is completely divorced from the version of VSTest, it's not possible for us to keep that up to date appropriately. We long ago put the dependency explicitly in the templates that unfold inside Visual Studio and `dotnet new xunit`, so I think the typical use case here isn't really broken. It's only for people who craft their `.csproj` files by hand that would be missing out on this reference.

I just double checked our docs page and it's out of date w/ respect to this (specifically, [this section](https://xunit.net/docs/getting-started/netfx/visual-studio#run-tests-visualstudio)), so I've opened an issue for that: https://github.com/xunit/xunit/issues/2209

**Comment by TysonMN** [comment]
Thanks @bradwilson.  That is a good improvement.

One thing I forgot to mention is that the error message when `Microsoft.NET.Test.Sdk` is missing could be better.  As shown in https://github.com/xunit/visualstudio.xunit/issues/219#issue-635703499, that message is currently something like
```
Unable to find /Users/user/dev/project/Commontests/bin/Debug/netcoreapp3.1/testhost.dll. Please publish your test project and retry.

Test Run Aborted.
```

Ideally it would say that `Microsoft.NET.Test.Sdk` is missing and that the fix is a add a direct dependency on it.  Maybe it could even include a link to the improved documentation that will result from https://github.com/xunit/xunit/issues/2209.
