### ISSUE TITLE
Assert.Single should fail rather than throw ArgumentNullException if the collection is null

### ISSUE THREAD

**Issue by gathogojr** [xunit/visualstudio.xunit#242]
`Assert.Single` method verifies that the given collection contains only a single element of the given type.
If the collection passed into the method is not initialized (i.e. it is `null`), an `ArgumentNullException` is thrown. I think the result should be an assertion failure instead. Such that one doesn't have to write two assertion statements as follows to accomplish that objective:
```csharp
Assert.NotNull(<collection>);
Assert.Single(<collection>);
```

**Comment by bradwilson** [comment]
This is expected behavior.

If you use 2.4.2 or later, and enable nullable reference checking, the compiler will emit a warning for you.

Test:

```csharp
#nullable enable

using System.Collections.Generic;
using Xunit;

public class UnitTest1
{
    [Fact]
    public void Test1()
    {
        IEnumerable<int>? x = null;

        Assert.Single(x);
    }
}
```

Compiler output:

`UnitTest1.cs(13,23): warning CS8604: Possible null reference argument for parameter 'collection' in 'int Assert.Single<int>(IEnumerable<int> collection)'`

If you check for null first, the compiler will no longer emit the message:

```csharp
IEnumerable<int>? x = null;

Assert.NotNull(x);
Assert.Single(x);
```
