### ISSUE TITLE
Support multiple test reporters

### ISSUE THREAD

**Issue by nvborisenko** [xunit/visualstudio.xunit#257]
Continuing https://github.com/xunit/xunit/pull/1863

Currently runner uses the first discovered test reporter, even if there are several available.

https://github.com/xunit/visualstudio.xunit/blob/2ab16095fae04b349c1c122c419ebd8bbc4c9c1f/test/test.xunit.runner.visualstudio/RunnerReporterTests.cs#L47-L58

What if runner will use all available reporters? Let's say I want to produce `xml` and `html` reports, or even more. In this case I would like to install mimic `XUnit.XmlReport` and `XUnit.HtmlReport` nuget packages, and get 2 different reports after tests execution.

@clairernovotny I am happy to provide PR with your guidance.

**Comment by bradwilson** [comment]
The design of reporters is for the real-time display of information to the user as the tests are running. They are not designed for results output; we already support output formatters, albeit not with VSTest (since they capture and report everything, so their standardized mechanism is for .TRX results files).
