### ISSUE TITLE
IXunitserializable does not serialize *any* data from the MemberData field

### ISSUE THREAD

**Issue by dougclutter** [xunit/visualstudio.xunit#269]
**Observed Behavior:**
-  When run via **dotnet test** all test are run and fail as expected and the correct count of 8 is shown:  
    Test Run Failed.
    Total tests: 8
         Failed: 8
- When run in VS 16.9.3 the following happens:
  - Test1, Test2, and Test3 run as expected
  - Test4 uses MemberData with 3 objects that implement IXunitserializable
  - Test4 runs only 1 test with a default value *not* one of the values from MemberData
 
**Expected Behavior:**
- Test4 should run 3 tests using data from the MemberData property

Attached is a simplified repo:
[Bug.IXunitserializable.zip](https://github.com/xunit/visualstudio.xunit/files/6298612/Bug.IXunitserializable.zip)

**Comment by bradwilson** [comment]
The problem is you didn't actually implement the serialization.

This:

```csharp
public class SerializableMemberData : LongLivedMarshalByRefObject, IXunitSerializable
{
    public int Value { get; set; }
    public void Serialize(IXunitSerializationInfo info)
    { }
    public void Deserialize(IXunitSerializationInfo info)
    { }
}
```

Needs to be this:

```csharp
public class SerializableMemberData : LongLivedMarshalByRefObject, IXunitSerializable
{
    public int Value { get; set; }
    public void Serialize(IXunitSerializationInfo info)
    {
        info.AddValue(nameof(Value), Value);
    }
    public void Deserialize(IXunitSerializationInfo info)
    {
        Value = info.GetValue<int>(nameof(Value));
    }
}
```

Because you didn't serialize any data, to the system it looks like you created three identical values (empty classes). The two duplicates get thrown away.

This is what I see with your code:

![image](https://github.com/xunit/visualstudio.xunit/assets/16944/046b14ba-e14a-4a83-87c5-e3ae799e21a8)

And this is what I see with my code:

![image](https://github.com/xunit/visualstudio.xunit/assets/16944/3691f30e-2d26-4930-a485-c5b474ac273f)
