### ISSUE TITLE
Support for VS 2015

### ISSUE THREAD

**Issue by joeloff** [xunit/visualstudio.xunit#31]
Is there an ETA for when the extension on the Visual Studio Gallery will be updated to include support for Visual Studio 2015?

**Comment by shederman** [comment]
I'm also not seeing any unit tests with Roslyn. Have added the NuGet test runner package as described by everyone above, and tests do NOT appear.

Since this seems to be affecting multiple people, and multiple projects, all using VS 2015 and XUnit; maybe the place to start is that it's a problem on the XUnit side?

**Comment by giggio** [comment]
@shederman I am working on an analyzers project with Roslyn on VS 2015 and all the tests show up.

**Comment by shederman** [comment]
The Roslyn xunit tests too? The only ones in the Roslyn project that show up for me are the non-XUnit C++ unit tests.

**Comment by bradwilson** [comment]
Visual Studio runner 0.99.9 ONLY supports Beta 5 when running xUnit.net v2 test projects. Roslyn has not yet upgraded to Beta 5.

**Comment by giggio** [comment]
@shederman An analyzers project that uses roslyn: https://github.com/code-cracker/code-cracker
Try opening and building, tests should show up.
