### ISSUE TITLE
VS Unit Test Explorer shows the same value for escaped and unescaped strings in XUnit test

### ISSUE THREAD

**Issue by adamint** [xunit/visualstudio.xunit#316]
Steps to reproduce:

1. Create an XUnit test project (this does not repro for MSTest)
2. Write a unit test with the following assertion: Assert.Equal("\r\n", "\\r\\n");
3. Run the unit test thru the unit test explorer
4. Note that the expected and actual strings are not equivalent, but they appear as so in the visual test detail summary. Like in MSTest unit tests, strings should not be escaped here and should appear verbatim.

![image](https://user-images.githubusercontent.com/20359921/169426483-90b8cb08-c8af-4215-bf7d-de5a288c8599.png)

**Comment by bradwilson** [comment]
There's something I don't understand about your repro case, because the test doesn't fail here (nor did I expect it to, because your provided example has equal strings):

![image](https://github.com/xunit/visualstudio.xunit/assets/16944/7e412f46-3c2c-4b92-aedf-f64340ac1f98)

Please provide a full repro project. Thanks!

**Comment by bradwilson** [comment]
Closing for lack of response. Please open a new issue if this is still a problem. Thanks!
