### ISSUE TITLE
DLLs not copied on linux with multi targets

### ISSUE THREAD

**Issue by Karql** [xunit/visualstudio.xunit#336]
Hi!

I have csproj with multi targets like this:

```xml
  <PropertyGroup>
    <TargetFrameworks>net472;net6.0</TargetFrameworks>
    <TargetFramework Condition="'$(OS)' != 'Windows_NT'">net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>10.0</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
```

When project is building on linux dlls:
- `xunit.runner.reporters.netcoreapp10.dll`
- `xunit.runner.utility.netcoreapp10.dll`
- `xunit.runner.visualstudio.dotnetcore.testadapter.dll`
are not copied to output directory.

Screen from linux:
![screen-build-linux](https://user-images.githubusercontent.com/173098/185066617-d9282d70-65c8-421f-8e12-14ba3249e142.png)

On windows it is ok:
![screen-build-win](https://user-images.githubusercontent.com/173098/185066673-71d86bf2-3e60-48d4-ad32-427b18ef17ae.png)

There for tests do not start (`dotnet test --no-build -f net6.0 --verbosity quiet --nologo --collect:"XPlat Code Coverage" xUnitMultiTargetIssue/xUnitMultiTargetIssue.csproj`):
![screen-execute-linux](https://user-images.githubusercontent.com/173098/185067918-62e0af6c-92eb-47de-9e93-99cb39265773.png)

`--no-build` is usted for pipeline reason.

After removing `<TargetFrameworks>net472;net6.0</TargetFrameworks>` dlls are copied corectly.

Sample repository with issue: https://github.com/Karql/xUnitMultiTargetIssue

Best regards,
Mateusz

**Comment by bradwilson** [comment]
The problem is you have conflicting `<TargetFrameworks>` vs. `<TargetFramework>`. What you're doing is setting two values, not overriding one (when you mean to do the latter). This is clearly confusing the build engine because you're expected to have one or the other, but not both.

Change the second `<TargetFramework>` to `<TargetFrameworks>` and it works as expected:

```xml
<TargetFrameworks>net472;net6.0</TargetFrameworks>
<TargetFrameworks Condition="'$(OS)' != 'Windows_NT'">net6.0</TargetFrameworks>
```

Before:

![image](https://github.com/xunit/visualstudio.xunit/assets/16944/88bfface-d2ef-46c7-af70-cdea0e11725b)

After:

![image](https://github.com/xunit/visualstudio.xunit/assets/16944/0abcff71-a5ac-46fc-abd3-e04983342b85)

**Comment by Karql** [comment]
@bradwilson thank you!
