### ISSUE TITLE
Cannot run XUnit Tests in non-English VS with xunit.runner.visualstudio 2.4.3

### ISSUE THREAD

**Issue by y87feng** [xunit/visualstudio.xunit#342]
Steps to reproduce:
Prepare ENU(English) OS, install VS language packs(Turkish, Chinese) and apply

1.Create a class library(FX 4.8)
2.Add NuGet package reference to xunit, xunit.runner.visualstudio (test adapter)
3.Add code in code editor 

```
        [Fact]
        public void TestMethod1()
        {
            Assert.Equal(1, 1);
        }
```

This is the settings in csproj file:
![image](https://user-images.githubusercontent.com/26366507/190768115-ff4c3099-61d9-46b8-9823-33f630eb3deb.png)

4. Run Test

Expected Result: Test should run passed in TE
 
Actual Result: Test cannot be discovered

Image:

![image](https://user-images.githubusercontent.com/26366507/190762397-708f20cf-caf9-4510-8a6b-fb73292fe23e.png)

Note: 
1. It's not repro on English VS

2. When downgrade `xunit.runner.visualstudio` from version 2.4.3 to 2.4.1, it works, looks like a regression

**Comment by DoctorKrolic** [comment]
Repros on Russial language for me as well. Please fix ASAP

**Comment by benutomo-dev** [comment]
I had a problem in my environment that may have the same cause.

In my case, when Visual Studio version 17.3.x, `xunit.runner.visualstudio` version 2.4.3 had no problem.
Immediately after updating Visual Studio to 17.4, tests for test projects with .NET Frawmework selected as the target framework cannot be run from the TestExplorer.

This problem is resolved by lowering the version of `xunit.runner.visualstudio` to 2.4.1.

My OS and Visual Studio language is Japanese.

**Comment by NecatiMeral** [comment]
I've observed the same issue on a german installation.
A rollback to 2.4.1 solved the issue.

**Comment by martinmueller4voice** [comment]
Can confirm that this regression (which cost me 2 days of tearing out my hair) happens with VS 2022 17.4.0 German.
Going back to 2.4.1 made VS run the tests again.

**Comment by bradwilson** [comment]
Is this still reproducible on version 2.4.5?

**Comment by lorcQc** [comment]
For my part, I can no longer reproduce the problem. Neither with version 2.4.5, nor with previous versions.

**Comment by bradwilson** [comment]
Thanks, I'll close the issue then.
