### ISSUE TITLE
License mismatch between nuget gallery and License.txt

### ISSUE THREAD

**Issue by arphox** [xunit/visualstudio.xunit#367]
Hi,

The [nuget gallery](https://www.nuget.org/packages/xunit.runner.visualstudio/2.4.5/) page states **MIT license**,  
the [License.txt](https://github.com/xunit/visualstudio.xunit/blob/main/License.txt) file states both **Apache 2.0** and MIT.

Which one is authoritative? Can you consolidate them, if possible, please?

Maybe linking the License.txt file in the nuget gallery page would be the best solution, I think it's possible.

**Comment by bradwilson** [comment]
We license our code with Apache 2, but we also include code from .NET which is licensed with MIT. We cannot consolidate, because we don't own all the code. You are potentially subject to both if you intend to modify the source code.

NuGet's auto-parsing has picked MIT. I'll see if there's something I can do to mark it as both, but I suspect it's going to be listed as one or the other.

**Comment by bradwilson** [comment]
It does not appear that there is any way for me to change this. You should feel free to open an issue with NuGet about proper detection and display of multi-licensed code.
