### ISSUE TITLE
dotnet test -- xUnit.LongRunningTestSeconds=1 does not appear to do anything

### ISSUE THREAD

**Issue by taori** [xunit/visualstudio.xunit#413]
I am trying to figure out why my unit tests are freezing on ubuntu.

I canceled this (and a couple other runs) https://github.com/taori/Amusoft.DotnetNew.Tests/actions/runs/10423060770 

In order to narrow down the source of the issue i tried to use this switch "-- xUnit.LongRunningTestSeconds=1" as specified in the docs. However this command does not appear to have any effect on windows at all, because when i write a test that does Task.Delay for 10 seconds the test still succeeds instead of timing out.

While it would be interesting to find out why the tests work fine on windows and fail on ubuntu it would probably also be good to find out why "-- xUnit.LongRunningTestSeconds=1" does not do anything, seeing how that is how i saw it in the docs [here](https://xunit.net/docs/runsettings#LongRunningTestSeconds)

**Comment by bradwilson** [comment]
`LongRunningTestSeconds` does not terminate tests which are running long; it merely reports them as diagnostic messages. If you haven't enabled diagnostic messages, you won't see these messages.

Additionally, `dotnet test` does not show diagnostic messages by default because it has a very low verbosity by default. You can override this by passing `--logger "console;verbosity=normal"` to turn the verbosity up so that diagnostic messages are visible.

If you want to terminate a test that's running too long, what you're looking for is `Timeout` parameter on `[Fact]` (or `[Theory]`).

**Comment by taori** [comment]
Oh okay. For some reason I thought this is a cli switch that times out long running tests for this test execution so that I don't have to set a timeout everywhere

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bradwilson** [comment]
The intention is just to help you locate an unexpectedly long running test so you'd know which test was being a problem, to determine which one to debug and/or decorate with a `Timeout`. 😄

**Comment by bradwilson** [comment]
Closing as there's nothing to fix.
