### ISSUE TITLE
Release notes link not working

### ISSUE THREAD

**Issue by MarioMajcicaAtABNAMRO** [xunit/visualstudio.xunit#430]
I was checking the release notes from the releases page in the GitHub. I noticed that the link specified is not working.

**Comment by bradwilson** [comment]
This is the complete list of release notes for `xunit.runner.visualstudio` since it started shipping separately from the core framework (minus a few releases by @clairernovotny without release notes other than whatever was auto-generated by GitHub): https://xunit.net/releases/visualstudio/

I'll see what I can do to fix the links to the older versions where the runner was co-released with the core framework.

**Comment by bradwilson** [comment]
I've updated all the links. I don't particularly understand GitHub's sort order here, but 🤷🏼 at least the links should all work now. 😄
